language: android

jdk: oraclejdk8

android:
  components:
    - tools
    - build-tools-25.0.2
    - platform-tools
    - android-25

before_script:
  - chmod +x gradlew

script:
   - ./gradlew assembleRelease
