apply plugin: 'com.android.library'

group = 'com.github.evotor'

android {
    namespace = "ru.evotor.devices.drivers"
    compileSdk 35
    defaultConfig {
        minSdkVersion 23
        targetSdkVersion 35
        versionCode 3_03_01_0
        versionName "3.3.1"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    buildFeatures {
        aidl = true
    }
}


apply plugin: 'maven-publish'
tasks.register("androidSourcesJar", Jar) {
    archiveClassifier.set("sources")
    // Указываем путь к исходникам библиотеки
    from(android.sourceSets.getByName("main").java.srcDirs)
}
afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.findByName('release')
                groupId = 'com.github.evotor'
                artifactId = 'device-drivers'
                version = 'v' + android.defaultConfig.versionName
                artifact tasks.named('bundleReleaseAar')
                artifact tasks.named('androidSourcesJar')
            }
        }
    }
}

dependencies {
    implementation 'org.jetbrains:annotations:15.0'
}
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}



